[[protocols]]
name = "Pioneer Bluray Player"
protocol = "nec"

[protocols.scancodes]
0xa6a7 = "REMOTE_PREFLIGHT"
0xafbc = "REMOTE_POWER"
0xa699 = "REMOTE_FUNCTION"
0xafb6 = "REMOTE_OPENCLOSE"
0xaff7 = "REMOTE_HOMEMEDIAGALLERY"
0xa63a = "REMOTE_RESOLUTION"
0xa6a0 = "REMOTE_PREFLIGHT2"
0xafec = "REMOTE_NETCONTENTS"
0xaf22 = "REMOTE_KEYLOCK"
0xa669 = "REMOTE_KARAOKE"
0xafe8 = "REMOTE_MICVOLUMEUP"
0xaff9 = "REMOTE_DIMMER"
0x6a19 = "REMOTE_SLEEP"
0xaf20 = "REMOTE_EXIT"
0xafe9 = "REMOTE_MICVOLUMEDOWN"
0xaf6a = "REMOTE_VIRTUALSOUND"
0xafb2 = "REMOTE_SOUND"
0xa60a = "REMOTE_VOLUMEUP"
0xaf2a = "REMOTE_CDSACD"
0xa60b = "REMOTE_VOLUMEDOWN"
0xaff3 = "REMOTE_USBREC"
0xa69d = "REMOTE_DISPLAY"
0xa61e = "REMOTE_MUTE"
0xafb4 = "REMOTE_TOPMENU"
0xafb9 = "REMOTE_POPUPMENU"
0xafe6 = "REMOTE_LEFT"
0xafe7 = "REMOTE_RIGHT"
0xafe5 = "REMOTE_DOWN"
0xa674 = "REMOTE_ENTER"
0xafb0 = "REMOTE_HOMEMENU"
0xaff4 = "REMOTE_RETURN"
0xaf24 = "REMOTE_REPLAY"
0xafb3 = "REMOTE_TOOLS"
0xafaa = "REMOTE_CONTINUED"
0xaf25 = "REMOTE_SKIPSEARCH"
0xaf3c = "REMOTE_REWIND"
0xaf39 = "REMOTE_PLAY"
0xaf3b = "REMOTE_FORWARD"
0xaf3e = "REMOTE_SKIPBACK"
0xaf3a = "REMOTE_PAUSE"
0xaf38 = "REMOTE_STOP"
0xaf3d = "REMOTE_SKIPNEXT"
0xa600 = "REMOTE_1"
0xa601 = "REMOTE_2"
0xa602 = "REMOTE_3"
0xa603 = "REMOTE_4"
0xa604 = "REMOTE_5"
0xa605 = "REMOTE_6"
0xa606 = "REMOTE_7"
0xa607 = "REMOTE_8"
0xa608 = "REMOTE_9"
0xa609 = "REMOTE_0"
0xafbe = "REMOTE_AUDIO"
0xaf36 = "REMOTE_SUBTITLE"
0xafb5 = "REMOTE_ANGLE"
0xa641 = "REMOTE_CLEAR"
0xa695 = "REMOTE_REPEAT"
0xafe4 = "REMOTE_AB"
0xaf60 = "REMOTE_PROGRAM"
0xaf61 = "REMOTE_BOOKMARK"
0xaf62 = "REMOTE_ZOOM"
0xaf63 = "REMOTE_INDEX"

[[protocols]]
name = "TV controls"
protocol = "rc5"

[protocols.scancodes]
0x0c = "REMOTE_TV_POWER2"
0x20 = "REMOTE_TV_CHANNELUP"
0x10 = "REMOTE_TV_VOLUMEUP"
0x28 = "REMOTE_TV_INPUT"
0x21 = "REMOTE_TV_CHANNELDOWN"
0x11 = "REMOTE_TV_VOLUMEDOWN"
