[[protocols]]
name = "Hisense EN2BF27H"
protocol = "necx"

[protocols.scancodes]
0xbf0d = "REMOTE_POWER"
0xbf12 = "REMOTE_INPUT"
0xbf01 = "REMOTE_1"
0xbf02 = "REMOTE_2"
0xbf03 = "REMOTE_3"
0xbf04 = "REMOTE_4"
0xbf05 = "REMOTE_5"
0xbf06 = "REMOTE_6"
0xbf07 = "REMOTE_7"
0xbf08 = "REMOTE_8"
0xbf09 = "REMOTE_9"
0xbf00 = "REMOTE_0"
0xbf3a = "REMOTE_GUIDE"
0xbf1f = "REMOTE_SUBTITLE"
0xbf52 = "REMOTE_RED"
0xbf53 = "REMOTE_GREEN"
0xbf54 = "REMOTE_YELLOW"
0xbf55 = "REMOTE_BLUE"
0xbf14 = "REMOTE_TEXT"
0xbf45 = "REMOTE_TXT"
0xbf16 = "REMOTE_UP"
0xbf19 = "REMOTE_LEFT"
0xbf18 = "REMOTE_RIGHT"
0xbf17 = "REMOTE_DOWN"
0xbf15 = "REMOTE_OK"
0xbf48 = "REMOTE_BACK"
0xbf5c = "REMOTE_EXIT"
0xbf20 = "REMOTE_HOME"
0xbf44 = "REMOTE_VOLUMEUP"
0xbf43 = "REMOTE_VOLUMEDOWN"
0xbf21 = "REMOTE_CHLIST"
0xbf0e = "REMOTE_MUTE"
0xbf4a = "REMOTE_CHANNELUP"
0xbf4b = "REMOTE_CHANNELDOWN"
0xbf58 = "REMOTE_REWIND"
0xbfa8 = "REMOTE_PLAY"
0xbf59 = "REMOTE_FORWARD"
0xbfa9 = "REMOTE_PAUSE"
0xbfbe = "REMOTE_AUDIOONLY"
0xbf5a = "REMOTE_STOP"
0xbf5f = "REMOTE_APPS"
0xbfaa = "REMOTE_YOUTUBE"
0xbf47 = "REMOTE_NETFLIX"
0xbf39 = "REMOTE_RAKUTENTV"
