[[protocols]]
name = "Telefunken QU50K800"
protocol = "rc5"

[protocols.scancodes]
0x10c = "REMOTE_POWER"
0x138 = "REMOTE_INPUT"
0x101 = "REMOTE_1"
0x102 = "REMOTE_2"
0x103 = "REMOTE_3"
0x104 = "REMOTE_4"
0x105 = "REMOTE_5"
0x106 = "REMOTE_6"
0x107 = "REMOTE_7"
0x108 = "REMOTE_8"
0x109 = "REMOTE_9"
0x100 = "REMOTE_0"
0x10f = "REMOTE_LANGUAGE"
0x13c = "REMOTE_TXT"
0x110 = "REMOTE_VOLUMEUP"
0x111 = "REMOTE_VOLUMEDOWN"
0x10d = "REMOTE_MUTE"
0x130 = "REMOTE_HOME"
0x120 = "REMOTE_CHANNELUP"
0x121 = "REMOTE_CHANNELDOWN"
0x12f = "REMOTE_GUIDE"
0x112 = "REMOTE_INFO"
0x10a = "REMOTE_BACK"
0x125 = "REMOTE_EXIT"
0x114 = "REMOTE_UP"
0x113 = "REMOTE_DOWN"
0x115 = "REMOTE_LEFT"
0x116 = "REMOTE_RIGHT"
0x135 = "REMOTE_OK"
0x127 = "REMOTE_NETFLIX"
0x129 = "REMOTE_YOUTUBE"
0x13e = "REMOTE_AMAZONVIDEO"
0x11d = "REMOTE_RAKUTENTV"
0x11e = "REMOTE_TWITCH"
0x13b = "REMOTE_STAR1"
0x137 = "REMOTE_RED"
0x136 = "REMOTE_GREEN"
0x132 = "REMOTE_YELLOW"
0x134 = "REMOTE_BLUE"
0x11b = "REMOTE_REWIND"
0x131 = "REMOTE_PAUSE"
0x11c = "REMOTE_FORWARD"
0x133 = "REMOTE_RECORD"
0x119 = "REMOTE_PLAY"
0x118 = "REMOTE_STOP"
