[[protocols]]
name = "Generic RGB Color"
protocol = "nec"

[protocols.scancodes]
0x45 = "REMOTE_BRIGHTER"
0x46 = "REMOTE_DARKER"
0x47 = "REMOTE_POWER"
0x44 = "REMOTE_RED"
0x40 = "REMOTE_YELLOW
0x43 = "REMOTE_PINK"
0x07 = "REMOTE_GREEN"
0x15 = "REMOTE_CYAN"
0x09 = "REMOTE_ORANGE"
0x16 = "REMOTE_BLUE"
0x19 = "REMOTE_PURPLE"
0x0d = "REMOTE_WHITE"
0x0c = "REMOTE_15MIN"
0x18 = "REMOTE_30MIN"
0x5e = "REMOTE_60MIN"
0x08 = "REMOTE_PULSE"
0x1c = "REMOTE_CHRISTMAS"
